### ISSUE TITLE
About "n_share" in netD

### ISSUE THREAD

**Issue by mazzzystar** [bytedance/OMGD#12]
Thanks for your work! 
I noticed that in `distill.sh` the `n_shared` parameter was setted to be `5`
https://github.com/bytedance/OMGD/blob/e70a3cc4397808b933ed41fff2435a60b144b523/scripts/unet_pix2pix/cityscapes/distill.sh#L7

And  in discriminator `forward` code:
https://github.com/bytedance/OMGD/blob/e70a3cc4397808b933ed41fff2435a60b144b523/models/modules/discriminators.py#L102-L111

So actually those all 5 blocks are using `self.blockXs[-1]`, which means we only use one discriminator in `pix2pix` training, correct me if I'm wrong :-D

**Comment by WuJie1010** [comment]
Yes, our paper employs a single fully-shared discriminator, where n_share=5.
