### ISSUE TITLE
No such file or directory: 'real_stat/cityscapes_A.npz'

### ISSUE THREAD

**Issue by TomatoBoy90** [bytedance/OMGD#2]
在运行train和test的时候会出现No such file or directory: 'real_stat/cityscapes_A.npz'
这个文件在哪里可以获取？
`
Traceback (most recent call last):
  File "test.py", line 98, in <module>
    npz = np.load(opt.real_stat_path)
  File "/opt/AN/envs/OMGD/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'real_stat/cityscapes_A.npz'

`

**Comment by WuJie1010** [comment]
Thanks for your interest in our work, we have updated the README.md, you can prepare datasets following our instruction.
