### ISSUE TITLE
Why OMGD reduces latency time by 90%?

### ISSUE THREAD

**Issue by Wanggcong** [bytedance/OMGD#3]
Hi, thanks for the solid work. I have a question about the latency time. In Table 5 (arxiv), I am surprised OMGD reduces latency time by 90% on mobile phones? As I know, depthwise operations could slow down the latency time. OMGD contains depthwise and pointwise. How does OMGD get 10x speed up? What are the differences between servers and mobile phones (tflite toolkits)?  Thank you!

**Comment by WuJie1010** [comment]
The model we test on mobile phones is the U-Net sytle generator which do not contains depthwise and pointwise conv.
