### ISSUE TITLE
drn-d-105_ms_cityscapes.pth not found

### ISSUE THREAD

**Issue by zhuzhu18** [bytedance/OMGD#4]

**Comment by WuJie1010** [comment]
You can download a pre-trained DRN model drn-d-105_ms_cityscapes.pth from https://drive.google.com/drive/folders/0B_4LoEXGO1TwcmhzLXpWUVFEMXM?resourcekey=0-PMTQHtlWMtSBYozjajFLXAto to support mIoU computation
